[users]
admin = "admin"
guest = "guest"

[twilio]
account_sid = "ACxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
auth_token = "your_twilio_auth_token"
from_phone = "+1234567890"  # Twilio number
handler_phone = "+919876543210"  # Your handler's mobile number
